// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User interface {
	IsUser()
}

type Lesson struct {
	ID       string   `json:"id"`
	Subject  string   `json:"subject"`
	Summary  *string  `json:"summary"`
	Tutor    *Tutor   `json:"tutor"`
	Student  *Student `json:"student"`
	Duration int      `json:"duration"`
	Date     string   `json:"date"`
	Chat     string   `json:"chat"`
}

type NewStudent struct {
	Email      string `json:"email"`
	Password   string `json:"password"`
	ProfilePic string `json:"profilePic"`
}

type Student struct {
	ID         string `json:"id"`
	Email      string `json:"email"`
	ProfilePic string `json:"profilePic"`
}

func (Student) IsUser() {}

type Tutor struct {
	ID         string   `json:"id"`
	Email      string   `json:"email"`
	ProfilePic string   `json:"profilePic"`
	HourlyRate int      `json:"hourlyRate"`
	Bio        string   `json:"bio"`
	Rating     int      `json:"rating"`
	Education  []string `json:"education"`
	Subjects   []string `json:"subjects"`
}

func (Tutor) IsUser() {}
